#!/bin/sh

if [ ! -f psm-dashboard-config.json ]; then
  echo "ERROR: You have no 'psm-dashboard-config.json' file." >&2
  echo "       Please copy 'psm-dashboard-config.json.tmpl' to" >&2
  echo "       that name, edit as needed, and try again." >&2
  exit 1
fi

echo ""
echo "Fetching and combining data (this can take a long time)..."
./gather-info > $$-features-info.json.tmp
mv $$-features-info.json.tmp features-info.json
echo "Done."
echo ""

echo "Results placed in 'features-info.json'."

# You could view the reqs by running this any time:
#
#   $ ./format-reqs --output=human RTM.csv
#
# If you need to load them into Emacs (with `psm-load-reqs' 
# from psm-reqs.el), then do something like this:
#
#   $ ./format-reqs --output=elisp RTM.csv > RTM.el
#
# Then you can invoke `psm-load-reqs' on RTM.el.
