#!/bin/sh

# ./gather-info expects to find the CSV-formatted reqs in RTM.csv.
./reqs2csv > RTM.csv

echo ""
echo "Fetching and combining data (this can take a long time)..."
./gather-info > $$-features-info.json.tmp
mv $$-features-info.json.tmp features-info.json
echo "Done."
echo ""

echo "Results placed in 'features-info.json'."

# You could view the reqs by running this any time:
#
#   $ ./format-reqs --output=human RTM.csv
#
# If you need to load them into Emacs (with `psm-load-reqs' 
# from psm-reqs.el), then do something like this:
#
#   $ ./format-reqs --output=elisp RTM.csv > RTM.el
#
# Then you can invoke `psm-load-reqs' on RTM.el.
