#!/bin/sh

OUTPUT_FORMAT="${1}"

if [ "${1}" != "human" -a "${1}" != "elisp" ]; then
  echo 'Must pass "human" or "elisp" argument to indicate output format.' >&2
  echo '' >&2
  echo 'If "human", consider using in conjuction with dmgrep (see' >&2
  echo 'https://github.com/OpenTechStrategies/ots-tools/blob/master/dmgrep)' >&2
  echo 'to find requirements that match particular words or patterns.  E.g.:' >&2
  echo '' >&2
  echo './show-reqs human | dmgrep -d "===================================" configur' >&2
  echo '' >&2
  exit 1
fi

if [ "${OUTPUT_FORMAT}" = "elisp" ]; then 
  echo "("
fi

./reqs2csv > RTM.csv
./format-reqs --output="${OUTPUT_FORMAT}" RTM.csv

if [ "${OUTPUT_FORMAT}" = "elisp" ]; then 
  echo ")"
fi
